language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ms-npm' ]; then cd .. && eval "mv $currentfolder generator-ms-npm" && cd generator-ms-npm; fi

